name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Type check
      run: npx tsc --noEmit
    - name: Run tests
      run: npm test
    - name: Custom checks
      run: npm run my-custom-script
    - name: Use secret
      run: echo "Using secret $MY_SECRET"